# Generated by Django 4.1 on 2022-12-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'zadacha', 'verbose_name_plural': 'zadachi'},
        ),
    ]
