# Generated by Django 4.1 on 2022-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fizproperties',
            options={'verbose_name': 'физ хар-ка', 'verbose_name_plural': 'физ хар-ки'},
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field10',
            field=models.CharField(default=10, max_length=50, verbose_name='Опорная температура (К)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field11',
            field=models.CharField(default=11, max_length=50, verbose_name='Дипольный момент (Н*М^4)^0.5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field12',
            field=models.CharField(default=12, max_length=50, verbose_name='Стан. тепл. образ. при 298К (Дж/Кмоль)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field13',
            field=models.CharField(default=13, max_length=50, verbose_name='Тепл. парообр. при Т кип.нор. (Дж/Кмоль)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field14',
            field=models.CharField(default=14, max_length=50, verbose_name='Изобарн. потенц. (при н.у.) (Дж/Кмоль)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field2',
            field=models.CharField(default=2, max_length=50, verbose_name='Норм. темп. плавления (К)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field3',
            field=models.CharField(default=3, max_length=50, verbose_name='Норм. темп. кипения (К)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field4',
            field=models.CharField(default=4, max_length=50, verbose_name='Критическая темп (К)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field5',
            field=models.CharField(default=5, max_length=50, verbose_name='Критическое давление (Па)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field6',
            field=models.CharField(default=6, max_length=50, verbose_name='Критический обьем (M^3/Кмоль)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field7',
            field=models.CharField(default=7, max_length=50, verbose_name='Крит к-ент сжимаемости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field8',
            field=models.CharField(default=8, max_length=50, verbose_name='Фактор ацентричн. Питцера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fizproperties',
            name='field9',
            field=models.CharField(default=9, max_length=50, verbose_name='Плотность жидк. при опорн. темп. (Кг/М^3)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fizproperties',
            name='field1',
            field=models.CharField(max_length=50, verbose_name='Молекулярная масса'),
        ),
        migrations.AlterField(
            model_name='fizproperties',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
